Diff bind reorg
OpenOmics/chrom-seek pull request #45
Opened 2024-09-03 19:03 UTC by rroutsong

refactoring and reorganization of the differential binding analyses

2024-09-03 20:49 UTC, tovahmarkowitz requested changes

2024-09-03 20:49 UTC, tovahmarkowitz commented on bin/DiffBind_v2_Deseq2.Rmd
Can you please confirm that lines 101-113 of this file matches the lines in DiffBind_v2_load.R? And repeat on the other Rmd files?
Also can you add a subtitle to this file so that it matches the other new Rmd files?

2024-09-03 20:49 UTC, tovahmarkowitz commented on bin/DiffBind_v2_Deseq2.Rmd
To be clear, we want summits = T with macsNarrow and summits = F for all other peak callers. This is different from the previous version.

2024-09-03 20:49 UTC, tovahmarkowitz commented on bin/DiffBind_v2_Deseq2_block.Rmd
Line 185 is pointing to variable that doesn't exist in this Rmd.

2024-09-03 20:49 UTC, tovahmarkowitz commented on workflow/Snakefile
I think line 150 might be wrong here. Is that for UROPA? Because we want UROPA to only run "protTSS" right now.

2024-09-03 20:49 UTC, tovahmarkowitz commented on workflow/rules/dba.smk
Like in Snakefile peak_types should only be "protTSS" for now. The other ones will eventually be added back, but not right now.

2024-09-03 20:49 UTC, tovahmarkowitz commented on workflow/rules/dba.smk
Also can we change lines 59-62 to be:

`"Diffbind": "_Diffbind_fullList.bed",`

That's what I was picturing for dealing with UROPA and Diffbind after the changes.

The four lines here point to files that don't exist.

2024-09-03 21:17 UTC, rroutsong commented on bin/DiffBind_v2_Deseq2_block.Rmd
can you make a comment at the line in particular, line 185 (current) looks good to me


```{r MA_D}
try(dba.plotMA(DBAnalysisDeseq2, method = DBA_DESEQ2),silent=TRUE)
```

2024-09-03 21:19 UTC, rroutsong commented on bin/DiffBind_v2_Deseq2.Rmd
yes it works exactly that way

```r
if ( peakcaller == "macsNarrow" ) {
   summits <- TRUE
   print ("Narrow peak calling tool.")
   print ("Differential peaks are 250bp upstream and downstream of the summits.")
} else if (grepl("broad", samples$samples$Peaks[1])) {
   summits <- FALSE
   print ("Broad peak calling tool.")
   print ("Differential peaks are consensus peaks.")
} else {
   summits <- FALSE
   print ("Indeterminate peak calling tool.")
   print ("Differential peaks are consensus peaks.")
}
```

2024-09-03 21:27 UTC, rroutsong commented on workflow/Snakefile
yes that was original peak type annotations we can remove it for now

2024-09-03 21:42 UTC, rroutsong commented on workflow/rules/dba.smk
I can remove peak types other than protTSS.

I cannot make the second change, those files are created by their respective R markdowns, and making that change would break the DAG

2024-09-04 13:18 UTC, tovahmarkowitz commented on workflow/rules/dba.smk
Hmm... The Rmds should only be making fullList.txt at this point. They should not be producing any fullList.bed files. The only fullList.bed file being created should be accomplished by DiffBind_v2_load.R.

2024-09-04 13:20 UTC, tovahmarkowitz commented on bin/DiffBind_v2_Deseq2_block.Rmd
This was the code in question:
`D2i <- length(DBReportEdgeR)`

2024-09-04 14:30 UTC, tovahmarkowitz commented on workflow/rules/dba.smk
DBA report files should be txt format, not bed format.

2024-09-04 15:30 UTC, rroutsong commented on workflow/rules/dba.smk
you should choose a different name than full list to differentiate between the full list bed outputs and this report

2024-09-04 15:35 UTC, rroutsong commented on bin/DiffBind_v2_Deseq2_block.Rmd
I rewrote the if statement

from
```r
D2i <- length(DBReportEdgeR)
if (D2i == 0) {
   i=1
} else if (D2i > 500) {
   i=500
} else {
   i=D2i
}
```

to 

```r
D2i <- length(DBReportDeseq2)
i <- as.integer(min(c(500, as.integer(max(c(D2i, 1)))))
```

2024-09-04 17:47 UTC, skchronicles reviewed
Thank you for the updates! Let's wait on testing to finish before merging.

2024-09-10 02:11 UTC, rroutsong commented
Sorry for the delay this is ready for review, data can be found at `/data/OpenOmics/dev/datasets` @tovahmarkowitz @skchronicles

2024-10-24 20:49 UTC, closed without merging