Seperate ends
OpenOmics/chrom-seek pull request #57
Opened 2024-12-10 20:57 UTC by rroutsong

Separate rule hierarchy for paired and single end, incorporating cfCHiP in as another hierarchical import in `Snakemake`

2024-12-11 20:46 UTC, rroutsong commented
Waiting for test data sets to finish running before review, all data stored at `/data/OpenOmics/dev/datasets/outputs`

2024-12-23 21:31 UTC, rroutsong commented
Using the command `tree -I 'logfiles|resources|workflow|bin|config|config.json|failed_jobs_*|job_information_*|*.R*.fastq.gz|*.krona.html.files|*.sh|COMPLETED' $DIRONE > $DIRONE.tree

2024-12-27 19:38 UTC, rroutsong commented
> ```shell
> tree -I 'logfiles|resources|workflow|bin|config|config.json|failed_jobs_*|job_information_*|*.R*.fastq.gz|*.krona.html.files|*.sh|COMPLETED'
> ```

Commit https://github.com/OpenOmics/chrom-seek/pull/57/commits/27709bd7500443f89fa1cd6b2abe2009263ef6b0 fixes insert size metric diff problem

```diff
1c1
< w_blocking
---
> w_blocking_PREV
```

2024-12-30 14:13 UTC, tovahmarkowitz reviewed
Hey, I just looked through your changes in the PE-specific rules as your current test runs shouldn't affect them. I noticed a few small things that I would like addressed. Thanks for all the hard work.
Tovah

2024-12-30 14:13 UTC, tovahmarkowitz commented on workflow/rules/paired/peakcall.smk
Please rearrange to put the two macs rules next to each other. Also, neither rule needs ppqt as inputs anymore so please remove.

2024-12-30 14:13 UTC, tovahmarkowitz commented on workflow/rules/paired/trim_align_dedup.smk
Rule bam2bw is using the SE parameters right now, please go back and fix. Also, this rule should no longer rely on ppqt once you are done, so please remove it from the input parameters.

2024-12-30 16:19 UTC, rroutsong commented on workflow/rules/paired/trim_align_dedup.smk
The portion from the paired end conditional from the original rule was used, everything looks good, can you be more specific about what parameters you think are wrong.

Why did you put ppqt files in the input in the first place if you're not using them in the rule functionality?

2024-12-30 16:25 UTC, tovahmarkowitz commented on workflow/rules/paired/trim_align_dedup.smk
ppqt was needed as an input for all three of these rules only in SE conditions. Asya hardcoded it for all conditions because it was easier for her, but now that we want to turn off ppqt in the PE conditions that will be problematic. 

If you look at the updated PE versions of the macs rules, you'll see that the run command changes already removed the ppqt input requirements.

For bam2bw, if you look at the if statement in the version of the rule on main, PE should use the --centerReads flag, while the SE conditions should use the -e flag. You might have flipped them.

2024-12-30 16:26 UTC, rroutsong commented on workflow/rules/paired/trim_align_dedup.smk
If you're talking about `bam_cov_option` here's the original way it was set:

```shell
bam_cov_option={input.ppqt}
if [ \"""" + str(paired_end) + """\" == False ]; then
            ppqt_len=$(awk '{{print $1}}' {input.ppqt})
            bam_cov_option="-e ${{ppqt_len}}"
else 
            bam_cov_option=--centerReads
fi
```

So while you originally set it to `{input.ppqt}`, you then overwrite it with `bam_cov_option=--centerReads` in paired end scenarios.

2024-12-30 16:31 UTC, tovahmarkowitz commented on workflow/rules/paired/trim_align_dedup.smk
right, so can you remove bam_cov_option altogether and have it just automatically do whichever is correct for PE or SE?

2024-12-30 16:33 UTC, rroutsong commented on workflow/rules/paired/trim_align_dedup.smk
thats the way it is now...

`bam_cov_option=--centerReads` is the value for the paired end route

2024-12-30 16:35 UTC, rroutsong commented on workflow/rules/paired/trim_align_dedup.smk
It maybe confusing cause you have you're checking against `False` here instead of `True` which is unusual in this pipeline.

2024-12-30 16:41 UTC, rroutsong commented on workflow/rules/paired/trim_align_dedup.smk
Since we're removing ppqt from the input files as well, we will need to come up with a default for single end `bam2bw` since it depends on the length of the ppqt file.

2024-12-30 16:48 UTC, rroutsong commented on workflow/rules/paired/peakcall.smk
ppqt files are required part of single end peak calling rules will need to come up with defaults for macs2 parameter `--extsize` if removed

2024-12-30 16:50 UTC, tovahmarkowitz commented on workflow/rules/paired/peakcall.smk
I don't want to remove ppqt for the single end rules, only the paired-end ones. Sorry if I didn't make that clear.

2024-12-30 16:55 UTC, rroutsong commented on workflow/rules/paired/peakcall.smk
OK I think I addressed it how you want it, please look at the latest commit

2024-12-30 16:59 UTC, tovahmarkowitz commented on workflow/rules/paired/peakcall.smk
Everything you changed looks exactly how I wanted it, but could you also look at the bam2bw rule in the paired-end folder?

2024-12-30 17:06 UTC, rroutsong commented on workflow/rules/paired/peakcall.smk
alright updated

2025-01-09 16:58 UTC, skchronicles commented
@tovahmarkowitz Did you have a chance to review everything? Is this PR ready to merge?

2025-01-10 16:38 UTC, tovahmarkowitz requested changes
Hi Ryan,

This looks great! I just have a few minor cleanup requests so things are a little nicer before we do the actual pull request. I have a few other smaller things we still need to change to finish up this dealing with separate ends mess, but they would involve a few rules that need added/removed so they should probably wait until after this major update! Thank you so much!

Tovah

2025-01-10 16:38 UTC, tovahmarkowitz commented on workflow/rules/paired/trim_align_dedup.smk
Please fix rule dedup to remove extraneous params and stop module loading tools that are no longer relevant.

2025-01-10 16:38 UTC, tovahmarkowitz commented on workflow/rules/single/trim_align_dedup.smk
Please fix rule dedup and rule BWA to remove extraneous params and stop module loading tools that are no longer relevant.

2025-01-10 16:38 UTC, tovahmarkowitz commented on workflow/rules/single/trim_align_dedup.smk
rule ppqt can now have {ext} replaced with "sorted" for its inputs and outputs.

2025-01-10 17:56 UTC, rroutsong commented on workflow/scripts/grouping.py
yes it has the situation you're describing would lead to an `ImportError` being raised

2025-01-10 18:02 UTC, rroutsong commented
@tovahmarkowitz the changes you requested have broke the single end pipeline I will need to spend some time fixing it @skchronicles please do not merge yet

2025-01-10 18:07 UTC, rroutsong commented on workflow/rules/single/trim_align_dedup.smk
this is not true, `{ext}` needs to stay in this rule or missing input errors are raised for `{output_dir}/bam/ppqt/{sample}.Q5DD.ppqt.txt`

2025-01-10 18:10 UTC, tovahmarkowitz commented on workflow/rules/single/trim_align_dedup.smk
That's weird. It looks like you have two ppqt rules in this file one for "sorted" and one for "Q5DD". Can you make sure they're both being used correctly?

2025-01-10 19:05 UTC, skchronicles commented
@rroutsong Can you update `bin/ppqt_process.py` to write the parse fragment length to a file (similar to how it was setup before)? We don't want to print it to standard output because occasionally this file will need to be manually updated when we run into weird edge cases.

After taking a peek, it looks like different single-end rules that use this PPQT file as an input use slightly different file name that point to output from the different PPQT rules.

**Here are some example(s):**
![image](https://github.com/user-attachments/assets/f993bcee-a95c-44a5-b010-afb3408197d6)
![image](https://github.com/user-attachments/assets/be10b5a1-421a-438e-ac8b-646224c682db)
![image](https://github.com/user-attachments/assets/d8fc7c53-0c92-4764-890a-038d88408e69)

Can we just use the BAM PPQT output file instead (i.e. `{name}.Q5DD.ppqt.txt`)? This would ensure we are using a consistent set of files across the different rules. With that being said, can you update this rule below:
![image](https://github.com/user-attachments/assets/25222b38-1105-45c6-b4a2-b8d85d1839b3)

2025-01-10 19:09 UTC, rroutsong commented
Tovah as

2025-01-10 19:11 UTC, rroutsong commented
> @rroutsong Can you update `bin/ppqt_process.py` to write the parse fragment length to a file (similar to how it was setup before)? We don't want to print it to standard output because occasionally this file will need to be manually updated when we run into weird edge cases.
> 
> After taking a peek, it looks like different single-end rules that use this PPQT file as an input use slightly different file name that point to output from the different PPQT rules.
> 
> **Here are some example(s):** ![image](https://private-user-images.githubusercontent.com/18038345/402119999-f993bcee-a95c-44a5-b010-afb3408197d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY0MDksIm5iZiI6MTczNjUzNjEwOSwicGF0aCI6Ii8xODAzODM0NS80MDIxMTk5OTktZjk5M2JjZWUtYTk1Yy00NGE1LWIwMTAtYWZiMzQwODE5N2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDE5MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOGZjYWNlMzNiM2QzMjk0MzIyYTQyYWFjZDVkN2E5MjMyNmVmNzJiMjYwOTE1NzZiZDJhYWRjMGE5N2I4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Did1CIkloAynhKCsPOtJA2pK-twOGIrP4LKy1DHtq5c) ![image](https://private-user-images.githubusercontent.com/18038345/402120103-be10b5a1-421a-438e-ac8b-646224c682db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY0MDksIm5iZiI6MTczNjUzNjEwOSwicGF0aCI6Ii8xODAzODM0NS80MDIxMjAxMDMtYmUxMGI1YTEtNDIxYS00MzhlLWFjOGItNjQ2MjI0YzY4MmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDE5MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmOTNjMzhhYzdkYzJjOGVmNDc1YzRlOTRjZTE1ODU3YWUxMGNkODc0YjM2M2RmZjFhMTI5NDRjODg3MjQxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.srXUDrj3i53axS29oCpY5QI-nanTJWYON7e8N0JpLZk) ![image](https://private-user-images.githubusercontent.com/18038345/402120581-d8fc7c53-0c92-4764-890a-038d88408e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY0MDksIm5iZiI6MTczNjUzNjEwOSwicGF0aCI6Ii8xODAzODM0NS80MDIxMjA1ODEtZDhmYzdjNTMtMGM5Mi00NzY0LTg5MGEtMDM4ZDg4NDA4ZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDE5MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNmUzMDJmZjU2YTQ0MTdlZDc1ZDUyMGRkNTgyNTVjODhlNTk5NjU4MDllMzkzMGI3ZjRmMmM2NmZmY2MyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JPZGEq5lnSjcpcQTTtOkUb08M7_2elYJM1_Ce99-5aw)
> 
> Can we just use the BAM PPQT output file instead (i.e. `{name}.Q5DD.ppqt.txt`)? This would ensure we are using a consistent set of files across the different rules. With that being said, can you update this rule below: ![image](https://private-user-images.githubusercontent.com/18038345/402121360-25222b38-1105-45c6-b4a2-b8d85d1839b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MzY0MDksIm5iZiI6MTczNjUzNjEwOSwicGF0aCI6Ii8xODAzODM0NS80MDIxMjEzNjAtMjUyMjJiMzgtMTEwNS00NWM2LWI0YTItYjhkODVkMTgzOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDE5MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NDk4NWM5ZDVkNjE3ZGM3YWFiOGM4MzlhYTI4YzQzMjJjMTc0YWY2NTg0NzJhMDlmZDM4YWQwMjc0ZjM5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OHNrgorPcfYY1-Rw2bJaYShxPFBUPTA6xMiReHZwTBM)

Tovah asked to have the script written that way in the first place. We are going back and forth on review changes, one person asked it to be this way and the other asked it be the opposite. This pipeline works as is an produces the files in the same hierarchy as the main branch, what is the deal here?

2025-01-10 20:20 UTC, rroutsong commented
alright we have to re-run all the single end data due to the functional change of rules

2025-01-13 18:20 UTC, skchronicles approved these changes
Thank you @rroutsong for these awesome changes! Seperating the SE vs. PE logic really makes each of these rules more readable and easier to understand/follow.

2025-01-13 18:21 UTC, merged